create table "public"."shop" (
    "id" bigint generated by default as identity not null,
    "shop_name" text not null default 'where'::text,
    "commission" double precision not null default '90'::double precision
);


alter table "public"."shop" enable row level security;

alter table "public"."trade_head" add column "shop_id" bigint;

CREATE UNIQUE INDEX shop_name_key ON public.shop USING btree (shop_name);

CREATE UNIQUE INDEX shop_pkey ON public.shop USING btree (id);

alter table "public"."shop" add constraint "shop_pkey" PRIMARY KEY using index "shop_pkey";

alter table "public"."shop" add constraint "shop_commission_check" CHECK (((commission >= (0)::double precision) AND (commission <= (100)::double precision))) not valid;

alter table "public"."shop" validate constraint "shop_commission_check";

alter table "public"."shop" add constraint "shop_name_key" UNIQUE using index "shop_name_key";

alter table "public"."trade_head" add constraint "public_trade_head_shop_id_fkey" FOREIGN KEY (shop_id) REFERENCES shop(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."trade_head" validate constraint "public_trade_head_shop_id_fkey";

grant delete on table "public"."shop" to "anon";

grant insert on table "public"."shop" to "anon";

grant references on table "public"."shop" to "anon";

grant select on table "public"."shop" to "anon";

grant trigger on table "public"."shop" to "anon";

grant truncate on table "public"."shop" to "anon";

grant update on table "public"."shop" to "anon";

grant delete on table "public"."shop" to "authenticated";

grant insert on table "public"."shop" to "authenticated";

grant references on table "public"."shop" to "authenticated";

grant select on table "public"."shop" to "authenticated";

grant trigger on table "public"."shop" to "authenticated";

grant truncate on table "public"."shop" to "authenticated";

grant update on table "public"."shop" to "authenticated";

grant delete on table "public"."shop" to "service_role";

grant insert on table "public"."shop" to "service_role";

grant references on table "public"."shop" to "service_role";

grant select on table "public"."shop" to "service_role";

grant trigger on table "public"."shop" to "service_role";

grant truncate on table "public"."shop" to "service_role";

grant update on table "public"."shop" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."shop"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."shop"
as permissive
for select
to public
using (true);

INSERT INTO  shop(shop_name,commission)
VALUES ('the create',90); 

update trade_head 
set shop_id=(select id from shop limit 1)


alter table "public"."trade_head" alter column "shop_id" set not null;