create table "public"."store" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "store_name" text
);


alter table "public"."store" enable row level security;

alter table "public"."trade_head" add column "store_id" bigint;

CREATE UNIQUE INDEX store_pkey ON public.store USING btree (id);

alter table "public"."store" add constraint "store_pkey" PRIMARY KEY using index "store_pkey";

alter table "public"."trade_head" add constraint "trade_head_store_id_fkey" FOREIGN KEY (store_id) REFERENCES store(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."trade_head" validate constraint "trade_head_store_id_fkey";

grant delete on table "public"."store" to "anon";

grant insert on table "public"."store" to "anon";

grant references on table "public"."store" to "anon";

grant select on table "public"."store" to "anon";

grant trigger on table "public"."store" to "anon";

grant truncate on table "public"."store" to "anon";

grant update on table "public"."store" to "anon";

grant delete on table "public"."store" to "authenticated";

grant insert on table "public"."store" to "authenticated";

grant references on table "public"."store" to "authenticated";

grant select on table "public"."store" to "authenticated";

grant trigger on table "public"."store" to "authenticated";

grant truncate on table "public"."store" to "authenticated";

grant update on table "public"."store" to "authenticated";

grant delete on table "public"."store" to "service_role";

grant insert on table "public"."store" to "service_role";

grant references on table "public"."store" to "service_role";

grant select on table "public"."store" to "service_role";

grant trigger on table "public"."store" to "service_role";

grant truncate on table "public"."store" to "service_role";

grant update on table "public"."store" to "service_role";



